### ISSUE TITLE
Perform a release

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkiverse-mybatis#4]
So it can be included in registry.quarkus.io

**Comment by zhfeng** [comment]
@gastaldi can you guide me how to do a release ? Thanks

**Comment by gastaldi** [comment]
I forgot to paste the link for the page with instructions: https://github.com/quarkiverse/quarkiverse/wiki/Release

**Comment by zhfeng** [comment]
Sure, I will check the page.

**Comment by gastaldi** [comment]
If you could update the README with more information about the project that would be great too :wink:

**Comment by zhfeng** [comment]
yeah, it is exactly what I'm working on and do you know where to place the mybatis.adoc ? also is there any way to generate the documentation and make it availiable on https://quarkus.io/guides/mybatis ?

**Comment by gastaldi** [comment]
Well, there are some resistance from some core members in putting the guide in the quarkus.io/guides/ (we are still discussing that), therefore I suggest to add them in a `docs/` directory in your repository in the meantime (for anything more complex than the README).

**Comment by zhfeng** [comment]
Thanks @gastaldi - I just release the 0.0.1

**Comment by gastaldi** [comment]
Excellent! Good job!
